name: Dictum
options:
  bundleIdPrefix: com.dictum
  xcodeVersion: "16.2"
  deploymentTarget:
    macOS: "14.0"
  minimumXcodeGenVersion: "2.40"
  derivedDataPath: build

packages:
  FluidAudio:
    url: https://github.com/FluidInference/FluidAudio.git
    from: 0.8.0
  # MLX-Swift LLM для Qwen
  MLXSwiftLM:
    url: https://github.com/ml-explore/mlx-swift-lm
    from: 2.29.1

targets:
  Dictum:
    type: application
    platform: macOS
    sources:
      - path: Dictum
        excludes:
          - "**/.DS_Store"
      - path: sound
        type: folder
        buildPhase: resources
      - path: AppIcon.icns
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dictum.app
        MARKETING_VERSION: "1.92"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_ENTITLEMENTS: Dictum.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_IDENTITY: "-"
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        GENERATE_INFOPLIST_FILE: false
        ENABLE_HARDENED_RUNTIME: false
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
        PRODUCT_NAME: Dictum
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
    dependencies:
      - package: FluidAudio
        product: FluidAudio
      - package: MLXSwiftLM
        product: MLXLLM
      - package: MLXSwiftLM
        product: MLXLMCommon
    entitlements:
      path: Dictum.entitlements
